//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace İşTakipProjesi.Models.Baglantisql
{
    using System;
    using System.Collections.Generic;
    
    public partial class İsTakip
    {
        public int ID { get; set; }
        public string SorumluPersonel { get; set; }
        public string TalepEden { get; set; }
        public string Konu { get; set; }
        public string Departman { get; set; }
        public string Modul { get; set; }
        public string Tarih { get; set; }
        public string Durum { get; set; }
        public string Dosya { get; set; }
    }
}
