//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace İşTakipProjesi.Models.Baglantisql
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class İşTakipDbEntities : DbContext
    {
        public İşTakipDbEntities()
            : base("name=İşTakipDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AdminGiris> AdminGiris { get; set; }
        public virtual DbSet<İletisim> İletisim { get; set; }
        public virtual DbSet<İsTakip> İsTakip { get; set; }
        public virtual DbSet<Personel> Personel { get; set; }
        public virtual DbSet<OrtakAlan> OrtakAlan { get; set; }
    }
}
